# Generated by Django 5.1.3 on 2024-11-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_work_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
