# Generated by Django 5.1.3 on 2024-11-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_date',
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default='2024-01-02'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
